# ▼ 비밀 금고(secret) 파일 연결 (반드시 1번 줄에 작성)
spring.profiles.include=secret

spring.application.name=SmartFarmServer

# 1. 서버 포트 설정
server.port=8585

# 2. TiDB 드라이버 설정 (주소와 비밀번호는 secret 파일로 이동됨)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA 설정
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# 4. 파일 업로드 용량 및 기타 설정
server.tomcat.max-http-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.jackson.serialization.write-dates-as-timestamps=false